### ISSUE TITLE
KitronikZIPLEDs fails on Pico W due to re-used StateMachine

### ISSUE THREAD

**Issue by sjmurdoch** [KitronikLtd/Kitronik-Pico-Smart-Air-Quality-Board-MicroPython#3]
KitronikZIPLEDs in PicoAirQuality.py (at defb34915520a3c0597995ad0a6d7151f6d4e5d0) fails to load on the Pico W with the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "PicoAirQuality.py", line 302, in __init__
ValueError: StateMachine claimed by external resource
```

Specifically, the following line fails
```python
self.ZIPLEDs = StateMachine(4, self._ZIPLEDOutput, freq=8_000_000, sideset_base=Pin(20))
```

It looks like StateMachine 4 is already used, [perhaps for the SPI channel to the wireless module](https://github.com/raspberrypi/pico-sdk/blob/f396d05f8252d4670d4ea05c8b7ac938ef0cd381/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c#L89). I changed this to StateMachine 0 and it works, though the solution still seems a bit unsatisfactory with hardcoding a different state machine since that could be used in a different set of circumstances. The MicroPython PIO implementation doesn't appear to expose the SDK functions that allow searching for available PIO state machines, so perhaps nothing better can be done. With this caveat, my patch is attached as [StateMachine.patch](https://github.com/KitronikLtd/Kitronik-Pico-Smart-Air-Quality-Board-MicroPython/files/10784186/StateMachine.patch).

**Comment by JackAtKitronik** [comment]
Hi, thank you for pointing this out. We have added a more dynamic approach to claiming the StateMachine. The updates to this code can be found here:

https://github.com/KitronikLtd/Kitronik-Pico-Smart-Air-Quality-Board-MicroPython/commit/9735764cdef6d41c7422ca5b5e585c53819a74b1#diff-e56cab3565257f477b6df1c7c304bcdf196bb03b9803a78660ff116ef2f70012R65
