### ISSUE TITLE
Getting ETIMEDOUT on PicoW

### ISSUE THREAD

**Issue by jjcf89** [KitronikLtd/Kitronik-Pico-Smart-Air-Quality-Board-MicroPython#4]
I connected the PicoW to the air quality board and uploaded the PicoAirQuality.py file.  I am able to import the various functions but trying to instantiate either the bme688 or oled variable per the README.  Results in an ETIMEDOUT error.

The OLED shows a bunch of dots on it. Basically garbled output.

```
>>> from PicoAirQuality import KitronikBME688, KitronikOLED, KitronikRTC, KitronikZIPLEDs, KitronikBuzzer, KitronikDataLogger, KitronikOutputControl, KitronikButton
>>> 
>>> bme688 = KitronikBME688()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PicoAirQuality.py", line 672, in __init__
  File "PicoAirQuality.py", line 1113, in __init__
  File "PicoAirQuality.py", line 1151, in init_display
  File "PicoAirQuality.py", line 1198, in show
  File "PicoAirQuality.py", line 1069, in write_data
OSError: [Errno 110] ETIMEDOUT

>>> oled = KitronikOLED()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PicoAirQuality.py", line 1113, in __init__
  File "PicoAirQuality.py", line 1151, in init_display
  File "PicoAirQuality.py", line 1198, in show
  File "PicoAirQuality.py", line 1069, in write_data
OSError: [Errno 110] ETIMEDOUT
```

**Comment by JackAtKitronik** [comment]
Hi,

It seems to be a new issue with MicroPython 1.20.0 but increasing the I2C timeout in both the BME688 and OLED classes has fixed it for us.

Try the latest update of the library to see if this has helped.

Thanks,
Jack

**Comment by jjcf89** [comment]
Thanks for the quick update. I'll give it a shot.

**Comment by jjcf89** [comment]
I applied your update but it didn't help.  FYI, The ETIMEOUT happens nearly instantaneously so I'm not sure the timeout parameter is doing anything.

What did help is adding a 1ms sleep to the init_display() method.  Now the code launches and seems to be running fine.

```
    # Initialise the display settings and start the display clear
    def init_display(self):
        for cmd in (
            self.SET_DISP | 0x00,  # off
...
        ):  # on
            self.write_cmd(cmd)
            sleep_ms(1)
```

**Comment by jjcf89** [comment]
Also note your [Example Code Real_Setup_Test.py](https://github.com/KitronikLtd/Kitronik-Pico-Smart-Air-Quality-Board-MicroPython/tree/772da486bcca4777682a4644108b4216b4f66bf9/Example%20Code/Real_Setup_Test.py )
references `log.setupDataFields()` which doesn't exist.  I assume it's supposed to call `nameColumnHeadings()`?

**Comment by JackAtKitronik** [comment]
Interesting, we can't get your `sleep_ms` fix to work for us. Can you send a copy of your code so we can see what we are doing differently?

If you don't want to post your code here, you can send it to admin@kitronik.co.uk and reference the GitHub issue in the email.

And thanks for letting us know about the example code.

**Comment by jjcf89** [comment]
Here is my copy of [PicoAirQuality.py.txt](https://github.com/KitronikLtd/Kitronik-Pico-Smart-Air-Quality-Board-MicroPython/files/11924269/PicoAirQuality.py.txt), which should match yours plus the sleep_ms.

I was just running your [Real_Setup_Test.py](https://github.com/KitronikLtd/Kitronik-Pico-Smart-Air-Quality-Board-MicroPython/tree/772da486bcca4777682a4644108b4216b4f66bf9/Example%20Code/Real_Setup_Test.py)

**Comment by JackAtKitronik** [comment]
Thanks for your code.

Can you also let us know which version of MicroPython you are using?

This will also help us with issue #5.

**Comment by jjcf89** [comment]
micropython-firmware-pico-w-130623.uf2

**Comment by jjcf89** [comment]
Is that enough? Or is there a way to print the version within the terminal?

**Comment by JackAtKitronik** [comment]
> Is that enough?

Yes that's good. I have tried the code with that version of MicroPython on a Pico W and still cannot reproduce the errors.

Do you have anything else attached to the board?

Is there another Pico you have that you can test it with?

It might be a problem with your hardware that's causing the issue in the software. If you can send pictures of the top and bottom of your board, with the Pico and without the Pico attached to the board, over to [admin@kitronik.co.uk](mailto:admin@kitronik.co.uk) then we can get someone to have a look for you.

**Comment by jjcf89** [comment]
with the 1ms sleep, the OLED has been working smoothly. I wanted to let you know incase someone else saw the same issue.  

> Do you have anything else attached to the board?

I've attached an sps30 particle sensor to the uart pads on the bottom. But that was after the oled issue workaround was in place.

> Is there another Pico you have that you can test it with?

Yeah I can try a second one.

**Comment by jjcf89** [comment]
> Yeah I can try a second one.

nvm, I don't have the thru-hole header pins for the spare picos. doh.

**Comment by JackAtKitronik** [comment]
> nvm, I don't have the thru-hole header pins for the spare picos. doh.

No worries.

> with the 1ms sleep, the OLED has been working smoothly. I wanted to let you know incase someone else saw the same issue.

Good, I'm glad you've managed to sort it. Thanks, it's helpful for us to know for if another person has the same problem.
